FROM onsdigital/dp-concourse-tools-ubuntu-22:ubuntu22.4-jammy-20250126

RUN apt-get update && apt-get install tzdata

WORKDIR /app/

COPY dp-frontend-search-controller .

CMD ./dp-frontend-search-controller
